Update pytest
Ran into this issue [1]

    TypeError: required field "lineno" missing from alias

[1] https://github.com/pytest-dev/pytest/discussions/9195